// clock50to25.v

// Generated using ACDS version 23.1 991

`timescale 1 ps / 1 ps
module clock50to25 (
		input  wire  clk_in_clk,  //  clk_in.clk
		output wire  clk_out_clk, // clk_out.clk
		input  wire  reset_reset  //   reset.reset
	);

	clock50to25_pll_0 pll_0 (
		.refclk   (clk_in_clk),  //  refclk.clk
		.rst      (reset_reset), //   reset.reset
		.outclk_0 (clk_out_clk), // outclk0.clk
		.locked   ()             // (terminated)
	);

endmodule
